version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "${PWD}/db-data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"  # Expose port 5432 to connect to PostgreSQL from pgAdmin

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    logging:
      options:
        max-size: 10m
        max-file: "3"

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    logging:
      options:
        max-size: 10m
        max-file: "3"
    depends_on:
      - zookeeper

  local-runner:
    image: amazon/mwaa-local:2_9
    restart: always
    depends_on:
      - postgres
      - kafka
    environment:
      - LOAD_EX=y
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - "${PWD}/dags:/usr/local/airflow/dags"
      - "${PWD}/plugins:/usr/local/airflow/plugins"
      - "${PWD}/requirements:/usr/local/airflow/requirements"
      - "${PWD}/startup_script:/usr/local/airflow/startup"
    ports:
      - "8080:8080"
    command: local-runner
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
    env_file:
      - ./config/.env.localrunner
  pgadmin:
    container_name: aws-mwaa-local-runner-2_9-pgadmin-1
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Default pgAdmin credentials
      PGADMIN_DEFAULT_PASSWORD: root
      POSTGRES_PASSWORD: airflow  # This must match the `POSTGRES_PASSWORD` in the Postgres service
    ports:
      - "5050:80"  # Exposing pgAdmin on port 5050 for access via browser
    logging:
      options:
        max-size: 10m
        max-file: "3"